---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/employees":
    post:
      summary: Create an employee
      tags:
      - Employees
      parameters: []
      responses:
        '201':
          description: Employee created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: John
                last_name:
                  type: string
                  example: Doe
                job_title:
                  type: string
                  example: Software Engineer
                country:
                  type: string
                  example: USA
                salary:
                  type: number
                  format: float
                  example: 75000.0
                email:
                  type: string
                  example: john@example.com
                phone_number:
                  type: string
                  example: 123-456-7890
              required:
              - first_name
              - last_name
              - job_title
              - country
              - salary
              - email
              - phone_number
    get:
      summary: List employees
      tags:
      - Employees
      parameters:
      - name: page
        in: query
        description: Page number for pagination
        schema:
          type: integer
      - name: per_page
        in: query
        description: Number of employees per page
        schema:
          type: integer
      responses:
        '200':
          description: List employees with pagination
  "/employees/{id}":
    get:
      summary: Show an employee
      tags:
      - Employees
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Employee found
        '404':
          description: Employee not found
    patch:
      summary: Update an employee
      tags:
      - Employees
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Employee updated
        '404':
          description: Employee not found
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: John
                last_name:
                  type: string
                  example: Doe
                job_title:
                  type: string
                  example: Software Engineer
                country:
                  type: string
                  example: USA
                salary:
                  type: number
                  format: float
                  example: 75000.0
                email:
                  type: string
                  example: john@example.com
                phone_number:
                  type: string
                  example: '1234567890'
    delete:
      summary: Delete an employee
      tags:
      - Employees
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Employee deleted
        '404':
          description: Employee not found
  "/insights":
    get:
      summary: Get insights for country and job title
      tags:
      - Insights
      parameters:
      - name: country
        in: query
        required: true
        description: Required filter to get min, max, average, median salary and employee
          count for a specific country
        schema:
          type: string
      - name: job_title
        in: query
        required: false
        description: Optional filter to get average salary for a specific job title
        schema:
          type: string
      responses:
        '200':
          description: Insights retrieved
          content:
            application/json:
              examples:
                example:
                  value:
                    overall:
                      min_salary: 30000.0
                      max_salary: 250000.0
                      average_salary: 135000.0
                    job_title_average_salary:
                      job_title: Engineer
                      average_salary: 82500.0
                    total_employees: 7
                    median_salary: 150000.0
              schema:
                type: object
                properties:
                  overall:
                    type: object
                    properties:
                      min_salary:
                        type: number
                        format: float
                      max_salary:
                        type: number
                        format: float
                      average_salary:
                        type: number
                        format: float
                  job_title_average_salary:
                    type: object
                    properties:
                      job_title:
                        type: string
                      average_salary:
                        type: number
                        format: float
                  total_employees:
                    type: integer
                  median_salary:
                    type: number
                    format: float
        '400':
          description: Invalid request
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
